# Generated by Django 4.2.1 on 2023-05-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("author_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Authors",
                "db_table_comment": "Contains all authors for references",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("organisation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="JobField",
            fields=[
                ("info_id", models.AutoField(primary_key=True, serialize=False)),
                ("info_title", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("journal_id", models.AutoField(primary_key=True, serialize=False)),
                ("journal_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Journal",
                "db_table_comment": "Contains the ids and names of article journals",
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("info_id", models.AutoField(primary_key=True, serialize=False)),
                ("info_title", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuestionRelation",
            fields=[
                ("QR_id", models.AutoField(primary_key=True, serialize=False)),
                ("QR_title", models.CharField(max_length=100)),
                ("QR_description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "Question-relations",
                "db_table_comment": "This contains information about how a question/submitted question is related to a question",
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "question_id",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("excerpt", models.TextField(blank=True)),
                (
                    "contact",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.contact",
                    ),
                ),
            ],
            options={
                "db_table": "Current-questions",
                "db_table_comment": "These are the current questions that we have accepted from the submitted questions",
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                ("ref_id", models.AutoField(primary_key=True, serialize=False)),
                ("ref_title", models.CharField(max_length=100)),
                ("full_citation", models.TextField()),
                ("doi", models.CharField(max_length=50)),
                ("relevance", models.PositiveSmallIntegerField()),
                ("publish_date", models.DateField()),
                ("isbn", models.TextField()),
                ("authors", models.ManyToManyField(to="questions.author")),
                (
                    "journal_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.journal",
                    ),
                ),
            ],
            options={
                "db_table": "References",
                "db_table_comment": "Cotains all reference information",
            },
        ),
        migrations.CreateModel(
            name="RefType",
            fields=[
                ("rtype_id", models.AutoField(primary_key=True, serialize=False)),
                ("rtype_class", models.CharField(max_length=50)),
                ("class_description", models.TextField()),
            ],
            options={
                "db_table": "Reference-type",
                "db_table_comment": "A cyclic table that contains all types of references, the self-joini relation is to indicate whether one reference type is a subcategory of another.",
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                ("species_id", models.AutoField(primary_key=True, serialize=False)),
                ("genus", models.CharField(max_length=50, null=True)),
                ("species", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "Species",
            },
        ),
        migrations.CreateModel(
            name="SubmittedQuestions",
            fields=[
                (
                    "question_id",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("excerpt", models.TextField(blank=True)),
                (
                    "contact",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.contact",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.reference",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.species",
                    ),
                ),
            ],
            options={
                "db_table": "Submitted-questions",
                "db_table_comment": "These are the submitted questions from users that will undergo review",
            },
        ),
        migrations.CreateModel(
            name="RelatedQuestions",
            fields=[
                (
                    "related_question_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("relation_rate", models.IntegerField(null=True)),
                (
                    "QR_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.questionrelation",
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.questions",
                    ),
                ),
                (
                    "submitted_question_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.submittedquestions",
                    ),
                ),
            ],
            options={
                "db_table": "Related-questions",
                "db_table_comment": "This contains the parent-child relationships between questions. Hierarchical data.",
            },
        ),
        migrations.AddField(
            model_name="questions",
            name="reference",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.reference",
            ),
        ),
        migrations.AddField(
            model_name="questions",
            name="species",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.species",
            ),
        ),
        migrations.CreateModel(
            name="QuestionReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.questions",
                    ),
                ),
                (
                    "reference_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.reference",
                    ),
                ),
            ],
            options={
                "db_table": "Questions-references",
                "db_table_comment": "Table containing which references are tied to which questions",
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="job_field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.jobfield",
            ),
        ),
    ]
