# Generated by Django 4.1.7 on 2023-05-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                ("citation_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_citation", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CurrentQuestions",
            fields=[
                (
                    "question_id",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("excerpt", models.TextField(blank=True)),
                (
                    "citation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.citation",
                    ),
                ),
                (
                    "parent_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="questions.currentquestions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                ("species_id", models.AutoField(primary_key=True, serialize=False)),
                ("species_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SubmittedQuestions",
            fields=[
                (
                    "question_id",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("excerpt", models.TextField(blank=True)),
                (
                    "citation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.citation",
                    ),
                ),
                (
                    "parent_question",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.currentquestions",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.species",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="currentquestions",
            name="species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.species",
            ),
        ),
    ]
