# Generated by Django 4.2.1 on 2023-05-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions",
            old_name="excerpt",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="submittedquestions",
            old_name="excerpt",
            new_name="description",
        ),
    ]
