# Generated by Django 4.1.7 on 2023-05-16 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_submittedquestions_citation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submittedquestions",
            name="parent_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.currentquestions",
            ),
        ),
    ]
