# Generated by Django 4.1.7 on 2023-04-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_submittedquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.citation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.species'),
        ),
    ]
