# Generated by Django 4.2.1 on 2023-05-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_rename_excerpt_questions_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedquestions",
            name="parent_question",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.questions",
            ),
        ),
    ]
