# Generated by Django 4.2.1 on 2023-05-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_submittedquestions_parent_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.contact",
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.reference",
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.species",
            ),
        ),
        migrations.AlterField(
            model_name="submittedquestions",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.contact",
            ),
        ),
        migrations.AlterField(
            model_name="submittedquestions",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.reference",
            ),
        ),
        migrations.AlterField(
            model_name="submittedquestions",
            name="species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.species",
            ),
        ),
    ]
