# Generated by Django 4.2.1 on 2023-05-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0004_alter_questions_contact_alter_questions_reference_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="submittedquestions",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
