# Generated by Django 4.2.1 on 2023-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_alter_questions_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="submittedquestions",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
