# Generated by Django 4.2.1 on 2023-05-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_alter_questions_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relatedquestions",
            old_name="question_id",
            new_name="parent_id",
        ),
        migrations.RemoveField(
            model_name="relatedquestions",
            name="submitted_question_id",
        ),
        migrations.AddField(
            model_name="relatedquestions",
            name="child_question_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="questions.submittedquestions",
            ),
        ),
    ]
