# Generated by Django 4.2.1 on 2023-05-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_rename_question_id_relatedquestions_parent_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relatedquestions",
            old_name="child_question_id",
            new_name="child_id",
        ),
    ]
