# Generated by Django 4.2.1 on 2023-05-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_alter_relatedquestions_child_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedquestions",
            name="QR_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.questionrelation",
            ),
        ),
        migrations.AlterField(
            model_name="relatedquestions",
            name="relation_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
