# Generated by Django 4.2.1 on 2023-05-26 13:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0011_alter_relatedquestions_qr_id_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="questions",
            managers=[
                ("question_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
