# Generated by Django 4.2.1 on 2023-05-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0012_alter_questions_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="questions",
            managers=[],
        ),
    ]
