# Generated by Django 4.2.1 on 2023-05-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0013_alter_questions_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relatedquestions",
            old_name="related_question_id",
            new_name="id",
        ),
        migrations.AddField(
            model_name="questions",
            name="parent_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.questions",
            ),
        ),
        migrations.AlterField(
            model_name="relatedquestions",
            name="child_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_relation",
                to="questions.questions",
            ),
        ),
        migrations.AlterField(
            model_name="relatedquestions",
            name="parent_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_relation",
                to="questions.questions",
            ),
        ),
    ]
