# Generated by Django 4.2.1 on 2023-05-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0017_alter_submittedquestions_parent_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="job_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.jobfield",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.organisation",
            ),
        ),
    ]
