# Generated by Django 4.2.1 on 2023-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0018_alter_contact_job_field_alter_contact_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedquestions",
            name="citation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submittedquestions",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="submittedquestions",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="submittedquestions",
            name="job_field",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="submittedquestions",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="submittedquestions",
            name="organisation",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
