# Generated by Django 4.2.2 on 2023-06-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0020_alter_submittedquestions_species"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="author",
            table_comment=None,
        ),
    ]
