FROM python:3.9
ENV PYTHONUNBUFFERED 1
ENV DockerHome = /home/backend
RUN mkdir /backend 
WORKDIR /backend 
ADD . /backend/ 
RUN pip install -r requirements.txt
RUN ["python3", "manage.py", "collectstatic"]

FROM nginx 
# Removing default nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]

