# Generated by Django 4.2.2 on 2023-07-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0002_alter_submission_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="date",
        ),
        migrations.AddField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
