# Generated by Django 4.2.2 on 2023-07-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts_comments",
            "0004_rename_references_submission_submitted_references_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="reviewed_references",
        ),
    ]
