# Generated by Django 4.2.2 on 2023-07-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0004_reference_link"),
        ("posts_comments", "0005_remove_submission_reviewed_references"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionReferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="open_problems.reference",
                    ),
                ),
                (
                    "submission_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts_comments.submission",
                    ),
                ),
            ],
        ),
    ]
