# Generated by Django 4.2.2 on 2023-07-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0008_remove_submission_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmittedReferences",
            fields=[
                ("reference_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=15)),
                ("ref", models.TextField(blank=True, null=True)),
                (
                    "submission_id",
                    models.ManyToManyField(to="posts_comments.submission"),
                ),
            ],
        ),
    ]
