# Generated by Django 4.2.2 on 2023-07-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0009_submittedreferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submittedreferences",
            name="submission_id",
        ),
        migrations.AddField(
            model_name="submittedreferences",
            name="submission_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="posts_comments.submission",
            ),
        ),
    ]
