# Generated by Django 4.2.2 on 2023-07-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0011_alter_submittedreferences_submission_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="affiliation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
