# Generated by Django 4.2.2 on 2023-07-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts_comments",
            "0012_submission_affiliation_submission_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="question",
        ),
        migrations.AddField(
            model_name="comments",
            name="submission",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="posts_comments.submission",
            ),
            preserve_default=False,
        ),
    ]
