# Generated by Django 4.2.2 on 2023-07-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0013_remove_comments_question_comments_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts_comments.comments",
            ),
        ),
    ]
