# Generated by Django 4.2.2 on 2023-07-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0016_alter_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="alias",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
