# Generated by Django 4.2.2 on 2023-07-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0017_comment_alias_comment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
