# Generated by Django 4.2.4 on 2023-08-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0018_comment_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submissionreferences",
            options={"verbose_name": "User submissions and Linked References"},
        ),
        migrations.AlterModelOptions(
            name="submittedreferences",
            options={"verbose_name": "Submitted Reference"},
        ),
    ]
