# Generated by Django 4.2.2 on 2023-07-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theory",
            fields=[
                (
                    "theory_id",
                    models.BigIntegerField(
                        db_column="Theory_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "theorytitle",
                    models.CharField(
                        blank=True, db_column="TheoryTitle", max_length=40, null=True
                    ),
                ),
                (
                    "theorydesc",
                    models.TextField(blank=True, db_column="TheoryDesc", null=True),
                ),
            ],
            options={
                "db_table": "theory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TheoryProblem",
            fields=[
                (
                    "opinion",
                    models.OneToOneField(
                        db_column="Opinion_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="questions.openproblems",
                    ),
                ),
                ("species_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "theory_question",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TheoryReference",
            fields=[
                (
                    "ref",
                    models.OneToOneField(
                        db_column="Ref_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="questions.reference",
                    ),
                ),
            ],
            options={
                "db_table": "theory_reference",
                "managed": False,
            },
        ),
    ]
