# Generated by Django 4.2.2 on 2023-07-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0002_solutionsubmission_researchsubmission_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchsubmission",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="researchsubmission",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="researchsubmission",
            name="question",
        ),
        migrations.RemoveField(
            model_name="solutionsubmission",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="solutionsubmission",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="solutionsubmission",
            name="question",
        ),
        migrations.DeleteModel(
            name="Comments",
        ),
        migrations.DeleteModel(
            name="ResearchSubmission",
        ),
        migrations.DeleteModel(
            name="SolutionSubmission",
        ),
    ]
