# Generated by Django 4.2.2 on 2023-07-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_author_contact_jobfield_journal_openproblems_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="openproblems",
            table_comment="These are the current open problems that we have accepted from the submitted questions",
        ),
        migrations.AlterModelTable(
            name="openproblems",
            table="OpenProblems",
        ),
        migrations.AlterModelTable(
            name="problemrelation",
            table="Open-relations",
        ),
        migrations.AlterModelTable(
            name="questionreference",
            table="OP-references",
        ),
        migrations.AlterModelTable(
            name="relatedproblem",
            table="Related-problems",
        ),
        migrations.AlterModelTable(
            name="submittedproblems",
            table="Submitted-OP",
        ),
    ]
