# Generated by Django 4.2.2 on 2023-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0003_remove_researchsubmission_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="link",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
