# Generated by Django 4.2.2 on 2023-07-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0004_reference_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theory",
            name="parent_t_id",
        ),
        migrations.AlterUniqueTogether(
            name="theoryproblem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="theoryproblem",
            name="opinion",
        ),
        migrations.RemoveField(
            model_name="theoryproblem",
            name="theory_id",
        ),
        migrations.AlterUniqueTogether(
            name="theoryreference",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="theoryreference",
            name="ref",
        ),
        migrations.RemoveField(
            model_name="theoryreference",
            name="theory",
        ),
        migrations.DeleteModel(
            name="ProblemSpecies",
        ),
        migrations.DeleteModel(
            name="Species",
        ),
        migrations.DeleteModel(
            name="Theory",
        ),
        migrations.DeleteModel(
            name="TheoryProblem",
        ),
        migrations.DeleteModel(
            name="TheoryReference",
        ),
    ]
