# Generated by Django 4.2.2 on 2023-07-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0005_remove_theory_parent_t_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openproblems",
            old_name="question_id",
            new_name="problem_id",
        ),
        migrations.RenameField(
            model_name="openproblems",
            old_name="parent_question",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="submittedproblems",
            old_name="parent_question",
            new_name="parent_problem",
        ),
        migrations.RenameField(
            model_name="submittedproblems",
            old_name="question_id",
            new_name="problem_id",
        ),
    ]
