# Generated by Django 4.2.2 on 2023-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0007_rename_question_openproblems_parent_problem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="doi",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="isbn",
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="relevance",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
