# Generated by Django 4.2.2 on 2023-07-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0010_alter_reference_publish_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openproblems",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="submittedproblems",
            name="reference",
        ),
    ]
