# Generated by Django 4.2.2 on 2023-07-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0012_alter_openproblems_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openproblems",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submittedproblems",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
