# Generated by Django 4.2.2 on 2023-07-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0013_alter_openproblems_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuestionReference",
            new_name="ProblemReference",
        ),
    ]
