# Generated by Django 4.2.2 on 2023-07-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0014_rename_questionreference_problemreference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problemreference",
            old_name="question_id",
            new_name="problem_id",
        ),
    ]
