# Generated by Django 4.2.4 on 2023-08-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_problems', '0016_openproblems_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
