# Generated by Django 4.2.4 on 2023-08-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0017_alter_reference_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="journal_name",
            field=models.CharField(max_length=100),
        ),
    ]
