# Generated by Django 4.2.4 on 2023-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0018_alter_journal_journal_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="ref_title",
            field=models.CharField(max_length=150),
        ),
    ]
