# Generated by Django 4.2.4 on 2023-08-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0019_alter_reference_ref_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="openproblems",
            name="descendants_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
