# Generated by Django 4.2.4 on 2023-09-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0020_openproblems_descendants_count"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="reftype",
            table_comment="A cyclic table that contains all types of references,                 the self-joini relation is to indicate whether one reference type is a subcategory of another.",
        ),
    ]
