# Generated by Django 4.2.4 on 2023-09-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0022_alter_problemreference_table_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submittedproblems",
            old_name="citation",
            new_name="references",
        ),
    ]
