# Generated by Django 4.2.4 on 2023-09-12 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("open_problems", "0023_rename_citation_submittedproblems_references"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="contact",
            table_comment="This table contains the contact details of the person who submitted the question",
        ),
        migrations.AlterModelTable(
            name="contact",
            table="Contact",
        ),
    ]
