# Generated by Django 4.2.4 on 2023-09-18 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("open_problems", "0024_alter_contact_table_comment_alter_contact_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openproblems",
            options={"verbose_name": "Open Problem"},
        ),
        migrations.AlterModelOptions(
            name="problemreference",
            options={"verbose_name": "Open Problems and Linked References"},
        ),
        migrations.AlterModelOptions(
            name="submittedproblems",
            options={"verbose_name": "Submitted Problem"},
        ),
    ]
