# Generated by Django 4.2.2 on 2023-07-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0003_alter_theory_parent_t_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theory",
            name="parent_t_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="annotations.theory",
            ),
        ),
    ]
