# Generated by Django 4.2.2 on 2023-07-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0004_alter_theory_parent_t_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theory",
            old_name="theorydesc",
            new_name="theory_description",
        ),
        migrations.RenameField(
            model_name="theory",
            old_name="theorytitle",
            new_name="theory_title",
        ),
    ]
