# Generated by Django 4.2.4 on 2023-09-18 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0005_rename_theorydesc_theory_theory_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Theory",
            new_name="Subject",
        ),
    ]
