# Generated by Django 4.2.4 on 2023-09-18 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0006_rename_theory_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="theory_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="theory_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="parent_t_id",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="theory_title",
            new_name="title",
        ),
    ]
