# Generated by Django 4.2.4 on 2023-09-18 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("open_problems", "0025_alter_openproblems_options_and_more"),
        ("annotations", "0007_rename_theory_description_subject_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TheoryProblem",
            new_name="SubjectProblem",
        ),
        migrations.RenameModel(
            old_name="TheoryReferences",
            new_name="SubjectReferences",
        ),
    ]
