# Generated by Django 4.2.4 on 2023-09-18 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("open_problems", "0025_alter_openproblems_options_and_more"),
        ("annotations", "0008_rename_theoryproblem_subjectproblem_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="subjectproblem",
            table_comment="Relation table for each subject and open problem",
        ),
        migrations.RenameField(
            model_name="subjectproblem",
            old_name="theory",
            new_name="subject",
        ),
        migrations.RenameField(
            model_name="subjectreferences",
            old_name="theory",
            new_name="subject",
        ),
        migrations.AlterUniqueTogether(
            name="subjectreferences",
            unique_together={("ref", "subject")},
        ),
        migrations.AlterModelTable(
            name="subjectreferences",
            table="subject_reference",
        ),
    ]
