# Generated by Django 4.2.4 on 2023-10-09 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("open_problems", "0025_alter_openproblems_options_and_more"),
        ("annotations", "0010_alter_subject_table_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compounds",
            fields=[
                ("compound_id", models.AutoField(primary_key=True, serialize=False)),
                ("compound_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "Compounds",
                "db_table_comment": "Table for all compounds",
            },
        ),
        migrations.CreateModel(
            name="CompoundProblems",
            fields=[
                ("annotation_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "compound_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotations.compounds",
                    ),
                ),
                (
                    "open_problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_problems.openproblems",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
