# Generated by Django 4.2.4 on 2023-10-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0011_compounds_compoundproblems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gene",
            old_name="gene_id",
            new_name="id",
        ),
    ]
