# Generated by Django 4.2.4 on 2023-10-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0012_rename_gene_id_gene_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compounds",
            old_name="compound_id",
            new_name="id",
        ),
    ]
