# Generated by Django 4.2.4 on 2023-10-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0025_alter_openproblems_options_and_more"),
        ("annotations", "0013_rename_compound_id_compounds_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SpeciesProblems",
            new_name="SpeciesProblem",
        ),
        migrations.RenameModel(
            old_name="SubjectReferences",
            new_name="SubjectReference",
        ),
        migrations.RenameField(
            model_name="compoundproblems",
            old_name="compound_id",
            new_name="compound",
        ),
        migrations.RenameField(
            model_name="geneproblem",
            old_name="gene_id",
            new_name="gene",
        ),
    ]
